---
# Path to coverprofile file (output of `go test -coverprofile` command).
profile: cover.out

# When specified reported file paths will not contain local prefix
# in the output.
local-prefix: github.com/iktzdx/go-neetcode

# Holds coverage thresholds percentages, values should be in range [0-100].
threshold:
  # The minimum coverage that each file should have.
  file: 70
  # The minimum coverage that each package should have.
  package: 80
  # The minimum total coverage project should have.
  total: 95

# Holds regexp rules which will exclude matched files or packages
# from coverage statistics.
exclude:
  # Exclude files or packages matching their paths.
  paths:
    - main.go
    - trees/helpers.go
    - graphs/graphs.go
